# Generated by Django 2.1.11 on 2020-02-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0005_auto_20200226_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookee_username', models.CharField(max_length=254)),
                ('customer_name', models.CharField(max_length=60)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_contact', models.CharField(max_length=12, unique=True)),
                ('booking_purpose', models.CharField(blank=True, max_length=254)),
                ('booked_room_number', models.IntegerField(unique=True)),
                ('booking_date_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.DateAndSlot')),
            ],
        ),
    ]
