# Generated by Django 2.1.11 on 2020-02-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooking',
            name='bookee_username',
        ),
    ]
