# Generated by Django 3.0.3 on 2020-03-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_date_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.DateAndSlot'),
        ),
    ]
