# Generated by Django 2.1.11 on 2020-02-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customerbooking_bookee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooking',
            name='bookee_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
