# Generated by Django 2.1.11 on 2020-02-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerbooking_bookee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooking',
            name='bookee_name',
        ),
    ]
