# Generated by Django 3.0.3 on 2020-03-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_roombooking_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='is_booked',
        ),
    ]
