# Generated by Django 2.1.11 on 2020-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customerbooking_bookee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooking',
            name='bookee_username',
            field=models.CharField(default='Admin', max_length=50, unique=True),
        ),
    ]
