# Generated by Django 2.1.11 on 2020-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerbooking_bookee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbooking',
            name='bookee_username',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
