# Generated by Django 3.0.3 on 2020-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateAndSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_slot', models.TimeField(choices=[('S1', '10:00:00'), ('S2', '20:00:00')])),
            ],
        ),
    ]
