# Generated by Django 3.0.3 on 2020-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_room_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='dateandslot',
            unique_together={('booking_date', 'booking_slot')},
        ),
    ]
