# Generated by Django 3.0.3 on 2020-03-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200303_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
