# Generated by Django 2.1.11 on 2020-02-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_trailmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trailmodel',
        ),
    ]
