# Generated by Django 2.1.11 on 2020-02-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_delete_trailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateandslot',
            name='booking_slot',
            field=models.TextField(choices=[('Slot 1', 'S1'), ('Slot 2', 'S2')]),
        ),
    ]
