# Generated by Django 3.0.3 on 2020-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200303_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateandslot',
            name='rooms_added',
            field=models.BooleanField(default=False),
        ),
    ]
