# Generated by Django 3.0.3 on 2020-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateandslot',
            name='booking_date',
            field=models.DateField(unique=True),
        ),
    ]
