# Generated by Django 3.0.3 on 2020-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20200301_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablerooms',
            name='rooms_available',
            field=models.IntegerField(),
        ),
    ]
